---
swagger: "2.0"
info:
  title: Red Hat Event API
  version: 1.1.0
  description: Red Hat Event API v1.1 - An API that gives information about the Red
    Hat Event
paths:
  /location:
    get:
      responses:
        200:
          description: OK
      operationId: GetLocation
      summary: Get Location
      description: Get the location of the next RedHat Event
  /timeframe:
    get:
      responses:
        200:
          description: OK
      operationId: GetTimeframe
      summary: Get Timeframe
      description: Get the timeframe of the next RedHat Event
  /participants:
    get:
      responses:
        200:
          description: '"OK"'
      operationId: GetAllParticipants
      summary: GetParticipants
      description: Get All Participants
securityDefinitions:
  apikey:
    type: apiKey
    description: Use a 3scale API Key
    name: api-key
    in: header
security:
- apikey: []
